name: Analyze

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze with Linter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-pub-cache-${{ runner.os }}-

      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format --set-exit-if-changed .
